### ISSUE TITLE
允许报错

### ISSUE THREAD

**Issue by ffrankfeng** [quzard/SEU_Auto_Admission#1]
'STUDENT_TYPE'

**Comment by quzard** [comment]
啥

**Comment by ffrankfeng** [comment]
运行报错了
![image](https://user-images.githubusercontent.com/37799449/143562192-d49766cb-e936-45fb-904b-c51dfa5ee354.png)

![image](https://user-images.githubusercontent.com/37799449/143562118-22f88918-44ae-44f9-9b93-c36a2cb00850.png)
